### ISSUE TITLE
Nice :)

### ISSUE THREAD

**Issue by FGRibreau** [therealbill/slammer#1]
Hello bill !

A readme would be nice, but reading the go code is enough to understand what is going on :)

slammer will be shared in our next [RedisWeekly](http://redisweekly.com) tomorrow morning (I added more explanation about what slammer is doing and how it can be useful), thanks for sharing @therealbill  :)

**Comment by therealbill** [comment]
Thanks, yeah I initially put it here to make it easier to distribute to my test machines, but I'll add a read tonight. :)

**Comment by therealbill** [comment]
Ok, @FGRibreau I've added a README along with a few other .. niceties. ;)

BTW, https://github.com/sentinel-tools/eventilator might be of interest to RW readers. And it already has a readme. ;)

**Comment by FGRibreau** [comment]
@therealbill indeed!

Did not know about eventilator, thanks, I will share it in our next weekly :)
